name: Biome Lint & Formatter & TypeScript Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Run Biome Lint & Formatter
        run: npm run check

      - name: Run Biome Formatter (dry-run)
        run: npx biome format . --write=false

      - name: TypeScript type check
        run: npx tsc --noEmit 