name: Biome Lint & Formatter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  biome-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Run Biome Lint
        run: npm run check
      - name: Run Biome Formatter (dry-run)
        run: npx biome format . 