name: CI

on:
  push:
    branches:
      - '**'
jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: Run Biome Lint
        run: npm run check
      - name: Run Biome Formatter (dry-run)
        run: npx biome format src/

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-node-deps
      - name: TypeScript type check
        run: npx tsc --noEmit 